mqtt:
  number:
    - name: senseowifi_pulse_dur_led_slow
      unique_id: uniqueid__senseowifi_pulse_dur_led_slow
      icon: mdi:led-on
      state_topic: "homie/senseowifi1/params/pulseDurLedSlow"
      command_topic: "homie/senseowifi1/params/pulseDurLedSlow/set"
      min: 10
      max: 5000
      step: 10
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_pulse_dur_led_fast
      unique_id: uniqueid__senseowifi_pulse_dur_led_fast
      icon: mdi:led-on
      state_topic: "homie/senseowifi1/params/pulseDurLedFast"
      command_topic: "homie/senseowifi1/params/pulseDurLedFast/set"
      min: 10
      max: 1000
      step: 5
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_pulse_dur_tolerance
      unique_id: uniqueid__senseowifi_pulse_dur_tolerance
      icon: mdi:delta
      state_topic: "homie/senseowifi1/params/pulseDurTolerance"
      command_topic: "homie/senseowifi1/params/pulseDurTolerance/set"
      min: 0
      max: 100
      step: 1
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_pulse_cont_threshold
      unique_id: uniqueid__senseowifi_pulse_cont_threshold
      icon: mdi:timer-sand
      state_topic: "homie/senseowifi1/params/pulseContThreshold"
      command_topic: "homie/senseowifi1/params/pulseContThreshold/set"
      min: 10
      max: 10000
      step: 10
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_heating_time
      unique_id: uniqueid__senseowifi_heating_time
      icon: mdi:heat-wave
      state_topic: "homie/senseowifi1/params/HeatingTime"
      command_topic: "homie/senseowifi1/params/HeatingTime/set"
      min: 10
      max: 300
      step: 1
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_heating_time_tol
      unique_id: uniqueid__senseowifi_heating_time_tol
      icon: mdi:heat-wave
      state_topic: "homie/senseowifi1/params/HeatingTimeTol"
      command_topic: "homie/senseowifi1/params/HeatingTimeTol/set"
      min: 0
      max: 100
      step: 1
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_brew1cup_seconds
      unique_id: uniqueid__senseowifi_brew1cup_seconds
      icon: mdi:coffee
      state_topic: "homie/senseowifi1/params/Brew1CupSeconds"
      command_topic: "homie/senseowifi1/params/Brew1CupSeconds/set"
      min: 5
      max: 120
      step: 1
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_brew2cup_seconds
      unique_id: uniqueid__senseowifi_brew2cup_seconds
      icon: mdi:coffee
      state_topic: "homie/senseowifi1/params/Brew2CupSeconds"
      command_topic: "homie/senseowifi1/params/Brew2CupSeconds/set"
      min: 5
      max: 120
      step: 1
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_brew_heat1cup_seconds
      unique_id: uniqueid__senseowifi_brew_heat1cup_seconds
      icon: mdi:coffee
      state_topic: "homie/senseowifi1/params/BrewHeat1CupSeconds"
      command_topic: "homie/senseowifi1/params/BrewHeat1CupSeconds/set"
      min: 5
      max: 120
      step: 1
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_brew_heat2cup_seconds
      unique_id: uniqueid__senseowifi_brew_heat2cup_seconds
      icon: mdi:coffee
      state_topic: "homie/senseowifi1/params/BrewHeat2CupSeconds"
      command_topic: "homie/senseowifi1/params/BrewHeat2CupSeconds/set"
      min: 5
      max: 180
      step: 1
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_cup_debounce_interval
      unique_id: uniqueid__senseowifi_cup_debounce_interval
      icon: mdi:timer
      state_topic: "homie/senseowifi1/params/CupDebounceInterval"
      command_topic: "homie/senseowifi1/params/CupDebounceInterval/set"
      min: 0
      max: 2000
      step: 10
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_led_ignore_change_duration
      unique_id: uniqueid__senseowifi_led_ignore_change_duration
      icon: mdi:led-strip-variant
      state_topic: "homie/senseowifi1/params/LedIgnoreChangeDuration"
      command_topic: "homie/senseowifi1/params/LedIgnoreChangeDuration/set"
      min: 0
      max: 100
      step: 1
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_press_duration
      unique_id: uniqueid__senseowifi_press_duration
      icon: mdi:gesture-tap-hold
      state_topic: "homie/senseowifi1/params/pressDuration"
      command_topic: "homie/senseowifi1/params/pressDuration/set"
      min: 50
      max: 1000
      step: 10
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"
      
  switch:
    - name: senseowifi_power
      unique_id: uniqueid__senseowifi_power
      icon: mdi:power
      #
      state_topic: "homie/senseowifi1/machine/power"
      state_on: "true"
      state_off: "false"
      #
      command_topic: "homie/senseowifi1/machine/power/set"
      payload_on: "true"
      payload_off: "false"
      #
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

  binary_sensor:
    - name: senseowifi_out_of_water
      unique_id: uniqueid__senseowifi_out_of_water
      icon: mdi:water-off-outline
      #
      state_topic: "homie/senseowifi1/machine/outOfWater"
      payload_on: "true"
      payload_off: "false"
      device_class: problem
      #
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_cup_available
      unique_id: uniqueid__senseowifi_cup_available
      icon: mdi:coffee-outline
      #
      state_topic: "homie/senseowifi1/machine/cupAvailable"
      payload_on: "true"
      payload_off: "false"
      #
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_cup_full
      unique_id: uniqueid__senseowifi_cup_full
      icon: mdi:coffee
      #
      state_topic: "homie/senseowifi1/machine/cupFull"
      payload_on: "true"
      payload_off: "false"
      #
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

  sensor:
    - name: senseowifi_brewed_size
      unique_id: uniqueid__senseowifi_brewed_size
      icon: mdi:coffee-maker
      #
      state_topic: "homie/senseowifi1/machine/brewedSize"
      #
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_opstate
      unique_id: uniqueid__senseowifi_opstate
      icon: mdi:state-machine
      #
      state_topic: "homie/senseowifi1/machine/opState"
      #
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    ##############################################################################

    - name: senseowifi_debug
      unique_id: uniqueid__senseowifi_debug
      icon: mdi:comment-text-multiple-outline
      #
      state_topic: "homie/senseowifi1/machine/debug"
      #
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"
      #
      entity_category: diagnostic

    - name: senseowifi_rssi
      unique_id: uniqueid__senseowifi_rssi
      icon: mdi:signal-cellular-2
      #
      state_topic: "homie/senseowifi1/$stats/signal"
      state_class: measurement
      #
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"
      #
      device_class: signal_strength
      entity_category: diagnostic

    - name: senseowifi_uptime
      unique_id: uniqueid__senseowifi_uptime
      icon: mdi:av-timer
      #
      state_topic: "homie/senseowifi1/$stats/uptime"
      unit_of_measurement: "s"
      #
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

  ##############################################################################

  button:
    - name: senseowifi_brew_coffee_normal
      unique_id: uniqueid__senseowifi_brew_coffee_normal
      icon: mdi:coffee
      #
      command_topic: "homie/senseowifi1/machine/brew/set"
      payload_press: "1cup"
      #
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_brew_coffee_double
      unique_id: uniqueid__senseowifi_brew_coffee_double
      icon: mdi:coffee
      #
      command_topic: "homie/senseowifi1/machine/brew/set"
      payload_press: "2cup"
      #
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"
      
    - name: senseowifi_reboot
      unique_id: uniqueid__senseowifi_reboot
      icon: mdi:restart
      command_topic: "homie/senseowifi1/system/reboot/set"
      payload_press: "true"
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"
    - name: senseowifi_getsettings
      unique_id: uniqueid__senseowifi_getsettings
      icon: mdi:cog-outline
      command_topic: "homie/senseowifi1/system/getSettings/set"
      payload_press: "true"
      availability_topic: "homie/senseowifi1/$state"
      payload_available: "ready"
      payload_not_available: "lost"
  ##############################################################################

template:
  - sensor:
      - name: senseowifi_uptime_since
        unique_id: uniqueid__senseowifi_uptime_since
        state: >
          {% if is_state("sensor.senseowifi_uptime", "unavailable") %}
            "unavailable"
          {% else %}
            {{ ((as_timestamp(now() - timedelta(seconds=(states.sensor.senseowifi_uptime.state | int))) / 300) | round() * 300) | timestamp_local() }}
          {% endif %}
        icon: mdi:calendar-clock
        device_class: timestamp

##############################################################################
homeassistant:
  customize:
    switch.senseowifi_power:
      friendly_name: "SenseoWifi"
    binary_sensor.senseowifi_out_of_water:
      friendly_name: "SenseoWifi Empty tank alert"
    binary_sensor.senseowifi_cup_available:
      friendly_name: "SenseoWifi Cup detected"
    binary_sensor.senseowifi_cup_full:
      friendly_name: "SenseoWifi Cup full"
    sensor.senseowifi_brewed_size:
      friendly_name: "SenseoWifi Prepared coffees counter (small or large)"
    sensor.senseowifi_opstate:
      friendly_name: "SenseoWifi Operating state"
    sensor.senseowifi_debug:
      friendly_name: "SenseoWifi Debug messages"
    sensor.senseowifi_uptime:
      friendly_name: "SenseoWifi Uptime"
    sensor.senseowifi_rssi:
      friendly_name: "SenseoWifi Wi-Fi signal strength (RSSI)"
    button.senseowifi_brew_coffee_normal:
      friendly_name: "SenseoWifi Brew single cup"
    button.senseowifi_brew_coffee_double:
      friendly_name: "SenseoWifi Brew large cup"
    sensor.senseowifi_uptime_since:
      friendly_name: "SenseoWifi Last reboot"


##############################################################################

homeassistant:
  customize:
    switch.senseowifi_power:
      friendly_name: "SenseoWifi"
    binary_sensor.senseowifi_out_of_water:
      friendly_name: "SenseoWifi Wassertank leer Warnung"
    binary_sensor.senseowifi_cup_available:
      friendly_name: "SenseoWifi Tasse steht unter"
    binary_sensor.senseowifi_cup_full:
      friendly_name: "SenseoWifi Tasse voll"
    sensor.senseowifi_brewed_size:
      friendly_name: "SenseoWifi Zähler Kaffee-Brühungen (inkl. klein oder groß)"
    sensor.senseowifi_opstate:
      friendly_name: "SenseoWifi Operationszustand"
    sensor.senseowifi_debug:
      friendly_name: "SenseoWifi Debug-Nachrichten"
    sensor.senseowifi_uptime:
      friendly_name: "SenseoWifi Uptime"
    sensor.senseowifi_rssi:
      friendly_name: "SenseoWifi WLAN Signalstärke (RSSI)"
    button.senseowifi_brew_coffee_normal:
      friendly_name: "SenseoWifi Auslöser einfache Tasse brühen"
    button.senseowifi_brew_coffee_double:
      friendly_name: "SenseoWifi Auslöser große Tasse brühen"
    sensor.senseowifi_uptime_since:
      friendly_name: "SenseoWifi Letzter Neustart"

##############################################################################

input_boolean:
  senseowifi_brew_double_automated:
    name: "SenseoWifi Flag automatisch große Tasse brühen"
    initial: off
    icon: mdi:coffee

##############################################################################

automation:
  - id: "1636231455732"
    alias: Regel SenseoWifi ausschalten wenn zu lange im READY Zustand
    trigger:
      - platform: state
        entity_id: sensor.senseowifi_opstate
        to: "SENSEO_READY"
        for:
          minutes: 10
    action:
      - service: switch.turn_off
        entity_id: switch.senseowifi_power
      - service: mqtt.publish
        data:
          topic: "homie/senseo-wifi-rf21/machine/buzzer/set"
          payload: "tone4"

  ##############################################################################

  - id: "1611257542502"
    alias: Regel SenseoWifi Erinnerungston bei voller Tasse
    mode: single
    trigger:
      platform: state
      entity_id: binary_sensor.senseowifi_cup_full
      to: "on"
    action:
      - delay:
          minutes: 3
      - repeat:
          while:
            - condition: state
              entity_id: binary_sensor.senseowifi_cup_full
              state: "on"
            - condition: state # deal with a known firmware bug
              entity_id: binary_sensor.senseowifi_cup_available
              state: "on"
          sequence:
            - service: mqtt.publish
              data:
                topic: "homie/senseo-wifi-rf21/machine/buzzer/set"
                payload: "tone3"
            - delay:
                minutes: 1

  ##############################################################################

  - id: "1611257542601"
    alias: Regel SenseoWifi automatisch brühen (Schritt 1) Einschalten
    trigger:
      - platform: state
        entity_id: input_boolean.senseowifi_brew_double_automated
        to: "on"
    condition:
      - condition: state
        entity_id: switch.senseowifi_power
        state: "off"
    action:
      - service: mqtt.publish
        data:
          topic: "homie/senseo-wifi-rf21/machine/buzzer/set"
          payload: "tone4"
      - service: switch.turn_on
        entity_id: switch.senseowifi_power

  - id: "1611257542602"
    alias: Regel SenseoWifi automatisch brühen (Schritt 2) Brühen starten
    trigger:
      - platform: state
        entity_id: sensor.senseowifi_opstate
        to: "SENSEO_READY"
        for:
          seconds: 1 # let states settle
      - platform: state
        entity_id: input_boolean.senseowifi_brew_double_automated
        to: "on"
    condition:
      - condition: state
        entity_id: switch.senseowifi_power
        state: "on"
      - condition: state
        entity_id: sensor.senseowifi_opstate
        state: "SENSEO_READY"
      - condition: state
        entity_id: binary_sensor.senseowifi_out_of_water
        state: "off"
      - condition: state
        entity_id: binary_sensor.senseowifi_cup_available
        state: "on"
      - condition: state
        entity_id: binary_sensor.senseowifi_cup_full
        state: "off"
      - condition: state
        entity_id: input_boolean.senseowifi_brew_double_automated
        state: "on"
    action:
      - service: mqtt.publish
        data:
          topic: "homie/senseo-wifi-rf21/machine/brew/set"
          payload: "2cup"

  - id: "1611257542603"
    alias: Regel SenseoWifi automatisch brühen (Schritt 3) Ausschalten
    trigger:
      platform: state
      entity_id: sensor.senseowifi_opstate
      from: "SENSEO_BREWING"
      for:
        seconds: 1 # let states settle
    condition:
      - condition: state
        entity_id: input_boolean.senseowifi_brew_double_automated
        state: "on"
    action:
      - service: switch.turn_off
        entity_id: switch.senseowifi_power

  - id: "1611257542604"
    alias: Regel SenseoWifi automatisch brühen (Schritt 4) Flag löschen
    trigger:
      platform: state
      entity_id: switch.senseowifi_power
      to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.senseowifi_brew_double_automated
        state: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.senseowifi_brew_double_automated

  - id: "1611257542605"
    alias: Regel SenseoWifi automatisch brühen (Schritt 5) Buzzerbestätigung
    trigger:
      platform: state
      entity_id: input_boolean.senseowifi_brew_double_automated
      to: "off"
    action:
      - service: mqtt.publish
        data:
          topic: "homie/senseo-wifi-rf21/machine/buzzer/set"
          payload: "tone4"

  ##############################################################################
